### ISSUE TITLE
Internal pane seems to have broken

### ISSUE THREAD

**Issue by timbl** [SolidOS/solid-panes#221]
on timbl.com version
```
TypeError: Cannot read property 'quad' of undefined
  undefined
    TypeError: Cannot read property 'quad' of undefined  undefined
        at st (https://timbl.com/timbl/Automation/Library/Mashup/mashlib.js:6871:17)  undefined
        at Object.render (https://timbl.com/timbl/Automation/Library/Mashup/mashlib.js:64804:33)  undefined
        at renderPane (https://timbl.com/timbl/Automation/Library/Mashup/mashlib.js:65873:56)  undefined
        at HTMLImageElement.<anonymous> (https://timbl.com/timbl/Automation/Library/Mashup/mashlib.js:65905:37)

```

**Comment by timbl** [comment]
```
{buildTime: "2020-02-03T19:08:07Z", commit: "760c879d1d5d2cf1f22090d21b8a987027963512", npmInfo: {…}}
buildTime: "2020-02-03T19:08:07Z"
commit: "760c879d1d5d2cf1f22090d21b8a987027963512"
npmInfo: {solid-panes: "3.0.1", npm: "6.10.0", ares: "1.15.0", brotli: "1.0.7", cldr: "35.1", …}
__proto__: Object
```

**Comment by timbl** [comment]
This should have been fixed by https://files.gitter.im/inrupt/data-browser-team/1Dzm/solid-panes.diff
