### ISSUE TITLE
Cannot assign to read only property 'baseURI' of object '#<XMLDocument>' in RDFa parse

### ISSUE THREAD

**Issue by timbl** [SolidOS/solid-panes#40]
Just set up a pod on inrupt.net, I get the home page with a few options, I click into inbox, I created a new file and gave it a name. When I open the tree to edit (says Make It So...) I get an error on screen....
Outline.expand: Unable to fetch https://anthonydoherty.inrupt.net/inbox/First%20Document/index.html: Failed to load https://anthonydoherty.inrupt.net/inbox/First%20Document/index.html Fetcher: Error trying to parse https://anthonydoherty.inrupt.net/inbox/First%20Document/index.html as RDFa:
TypeError: Cannot assign to read only property 'baseURI' of object '#<XMLDocument>':
TypeError: Cannot assign to read only property 'baseURI' of object '#<XMLDocument>'
at t (https://anthonydoherty.inrupt.net/common/js/mashlib.min.js:6:308828)
at t.e (https://anthonydoherty.inrupt.net/common/js/mashlib.min.js:6:271548)
at t.e (https://anthonydoherty.inrupt.net/common/js/mashlib.min.js:6:274064)
at https://anthonydoherty.inrupt.net/common/js/mashlib.min.js:6:289130

from
https://gitter.im/solid/chat?at=5bafadc6bbdc0b2505bee8ee

**Comment by timbl** [comment]
I’ve raised it as a solid-panes bug solid/solid-panes#40 as that is where it shows up… It looks like in the RDFa parser it is trying to set a property which used to be writeable but has since maybe made read-only in the browser or something like that
