### ISSUE TITLE
MicroBlog pane is not loading

### ISSUE THREAD

**Issue by johanbove** [SolidOS/solid-panes#45]
The Microblog pane seems to be missing tabulator.
```
ReferenceError: tabulator is not defined undefined
ReferenceError: tabulator is not defined undefined at new m (https://adamthephantump.solid.community/common/js/mashlib.min.js:1731:39562) undefined at Object.render (https://adamthephantump.solid.community/common/js/mashlib.min.js:1731:43089)
 undefined at l (https://adamthephantump.solid.community/common/js/mashlib.min.js:79:326484) 
undefined at HTMLImageElement.<anonymous>
 (https://adamthephantump.solid.community/common/js/mashlib.min.js:79:326944)
```

**Comment by johanbove** [comment]
I can have a look at this.

**Comment by johanbove** [comment]
There are two global references to "tabulator.preferences" within microblogPane.js, which are set in package.json as globals. So... need to investigate further.

**Comment by johanbove** [comment]
See https://github.com/solid/solid-panes/pull/46

**Comment by johanbove** [comment]
I can also have a look at the Microblog CSS code. There are couple of older references that can be modernized. For instance ``-moz-border-radius:3px;`` can be safely replaced by ``border-radius:3px;``.
Also my fix also requires a change to package.json, as in ``UI`` should be added to the ``globals``.

**Comment by melvincarvalho** [comment]
So tabulator references are fixed in the current mashlib 

https://linkeddata.github.io/mashlib/dist/mashlib.min.js

We just need to push that to npm ... however a new issue

```
Error: Missing IRI for NamedNode
  undefined
    Error: Missing IRI for NamedNode  undefined
        at new t (https://linkeddata.github.io/mashlib/dist/mashlib.min.js:8:66992)  undefined
        at t.value (https://linkeddata.github.io/mashlib/dist/mashlib.min.js:116:31295)  undefined
        at new d (https://linkeddata.github.io/mashlib/dist/mashlib.min.js:144:458171)  undefined
        at Object.render (https://linkeddata.github.io/mashlib/dist/mashlib.min.js:144:462887)  undefined
        at https://linkeddata.github.io/mashlib/dist/mashlib.min.js:144:184798  undefined
        at HTMLImageElement.<anonymous> (https://linkeddata.github.io/mashlib/dist/mashlib.min.js:144:185194)
```

**Comment by johanbove** [comment]
The MicroBlog code is not easy to parse through. Noticed that the latest error here is not the same as the initial error; the first error mentioned ``FollowList``; what changed in the meantime?

```
Error: Missing IRI for NamedNode
  undefined
    Error: Missing IRI for NamedNode  undefined
        at new NamedNode (https://melvin.solid.live/common/js/mashlib.min.js:47174:13)  undefined
        at IndexedFormula.sym (https://melvin.solid.live/common/js/mashlib.min.js:43707:14)  undefined
        at new FollowList (https://melvin.solid.live/common/js/mashlib.min.js:67360:34)  undefined
        at Object.render (https://melvin.solid.live/common/js/mashlib.min.js:67600:24)  undefined
        at renderPane (https://melvin.solid.live/common/js/mashlib.min.js:69229:34)  undefined
        at HTMLImageElement.<anonymous> (https://melvin.solid.live/common/js/mashlib.min.js:69253:15)
```

Another version of this error:

```
Error: Missing IRI for NamedNode
  https://johanbove.solid.community/common/js/mashlib.min.js:8:66992
    t  https://johanbove.solid.community/common/js/mashlib.min.js:116:31295
    value  https://johanbove.solid.community/common/js/mashlib.min.js:144:458169
    d  https://johanbove.solid.community/common/js/mashlib.min.js:144:462887
    render  https://johanbove.solid.community/common/js/mashlib.min.js:144:184796
    e.exports/this.propertyTable/o</</</<  https://johanbove.solid.community/common/js/mashlib.min.js:144:184672
    e.exports/this.propertyTable/o</</<  undefined
```
